### ISSUE TITLE
Compilation fails under Eclipse

### ISSUE THREAD

**Issue by BitSalat** [JMare/esp-idf-bq27441#1]
Was happy to find your IDF implementation of the fuel gauge device however have difficulties to compile:

...
In file included from c:\users\sttauschek\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\xtensa-esp32-elf\sys-include\stdio.h:35,
                 from ../main/main.cpp:1:
C:/Users/sttauschek/Espressif/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:318:41: error: static assertion failed: portGET_ARGUMENT_COUNT() result does not match for 0 arguments
 _Static_assert(portGET_ARGUMENT_COUNT() == 0, "portGET_ARGUMENT_COUNT() result does not match for 0 arguments");
                                         ^
ninja: build stopped: subcommand failed.
Build complete (1 errors, 0 warnings): C:\Users\sttauschek\eclipse-workspace\esp-idf-bq27441\build

Can u help to fix that?

**Comment by JMare** [comment]
Hi @BitSalat,
This error rings a bell, I think I have seen it before.
What version of ESP-IDF are you compiling with?

**Comment by BitSalat** [comment]
Hi JMare,
thanx for your fast response - I am always working with Master branch of IDF which is now V4.3something.
I have also installed latest [Eclipse Espressif plugin](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.0.0) which is now Revision 2.0 (to be able to compile for the upcoming new SoCs -S2, S3 and -C3).
br - BitSalat

**Comment by JMare** [comment]
Hi, sorry for the slow response,
I believe the error to be to do with a bug when compiling as c++ in certain versions of ESP-IDF.
You could try compiling the example program as c, small code changes may be needed for this.
I would recommend trying with IDF 4.0 which I know works, but soon I will try and test with master.

**Comment by matti122** [comment]
Hi JMare and BitSalat,
I found the following commit which solved the issue at my site with the latest Master of esp-idf.
https://github.com/espressif/esp-idf/pull/6692/commits/d284e5b5d29afc10b6b8619baebdcd33b87d0a1e
Best regards
Matthias
